# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4c14cb65285350e7b0e2e3774915032c7845182597e2b3dd7ace9e252252abf4431984de5c4b1c27bd0ffb86d0866704ad6f1fe884e9c5e0195d3f739d9033

test:
  secret_key_base: 6c542db878e11e3e81581791919c6e4e817696bc61e5595f2799eadf495918c839dc900771cebe7094f153752b774e715eaf3d655a539d3e603d74cef8bd720c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
